name: ds-and-ml

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pytz
  - python-dotenv
  - yfinance
  - pip:
    - fredapi==0.5.*
